config { 
    type: "table"
}
SELECT
    a.ProductID
    , a.Name as ProductName
    , c.Name as ProductCategoryName    
    , b.Name as ProductSubcategoryName    
    , a.ProductNumber
    , a.Color
    , a.ListPrice
    , a.ProductLine
FROM
    ${ref("Product")} a
INNER JOIN
        ${ref("ProductSubcategory")} b
ON
    a.ProductSubcategoryID = b.ProductSubcategoryID
INNER JOIN
        ${ref("ProductCategory")} c
ON
    b.ProductCategoryID = c.ProductCategoryID